/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bo.patientmanager.gui;

import com.bo.patientmanager.gui.component.BackgroundPanel;
import com.bo.patientmanager.gui.component.CustomMessageDialog;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;

import com.bo.patientmanager.model.Patient;
import com.bo.patientmanager.model.Session;
import utils.time.DateMapper;
import com.bo.patientmanager.service.PatientService;
import com.bo.patientmanager.service.ServiceManager;
import com.bo.patientmanager.service.SessionService;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.UIManager;

/**
 *
 * @author Bring Online
 */
public class LoadPatientForm extends javax.swing.JPanel {
    
    private JDateChooser dtPatientBirthday;
    private PatientService patientService = null;
    private SessionService sessionService = null;


    /**
     * Creates new form LoadPatientForm
     */
    public LoadPatientForm(ServiceManager serviceManager) {
        initComponents();
        
        this.setOpaque(false);
        bg.setOpaque(false);
        
        dtPatientBirthday = new JDateChooser();
        dtPatientBirthday.setDateFormatString("dd/MM/yyyy");

        jPanelPatientBirthday.setLayout(new BorderLayout());
        jPanelPatientBirthday.add(dtPatientBirthday, BorderLayout.CENTER);
        
        this.patientService = serviceManager.getPatientService();
        this.sessionService = serviceManager.getSessionService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientLastName = new javax.swing.JTextField();
        txtPatientAddress = new javax.swing.JTextField();
        txtPatientCity = new javax.swing.JTextField();
        cmbPatientGender = new javax.swing.JComboBox<>();
        cmbPatientCountry = new javax.swing.JComboBox<>();
        jPanelPatientBirthday = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        txtPatientPhone2 = new javax.swing.JTextField();
        txtPatientEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPatientSocials = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPatientDifBillingRate = new javax.swing.JTextField();
        cmbPatientSessionDay1 = new javax.swing.JComboBox<>();
        cmbPatientSessionDay2 = new javax.swing.JComboBox<>();
        cmbPatientSessionHour1 = new javax.swing.JComboBox<>();
        cmbPatientSessionHour2 = new javax.swing.JComboBox<>();
        cmbPatientSessionDay3 = new javax.swing.JComboBox<>();
        cmbPatientSessionHour3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbPatientSessionMode1 = new javax.swing.JComboBox<>();
        cmbPatientSessionMode2 = new javax.swing.JComboBox<>();
        cmbPatientSessionMode3 = new javax.swing.JComboBox<>();
        cmbPatientCurrency = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtPatientDerivedFrom = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPatientInitialObservations = new javax.swing.JTextArea();
        btnSaveNewPatientForm = new javax.swing.JButton();
        btnClearPatientForm = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(232, 216, 255));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setPreferredSize(new java.awt.Dimension(863, 657));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(61, 25, 119));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargar nuevo paciente");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(61, 25, 119));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("País");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha Nac.");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Género");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Datos personales");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtPatientLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientLastNameActionPerformed(evt);
            }
        });

        txtPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientAddressActionPerformed(evt);
            }
        });

        txtPatientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientCityActionPerformed(evt);
            }
        });

        cmbPatientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Gay", "Lesbiana", "Trans F", "Trans M", "No Binario", "Otro" }));
        cmbPatientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientGenderActionPerformed(evt);
            }
        });

        cmbPatientCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "El Salvador", "Panamá", "Paraguay", "Perú", "Uruguay", "Venezuela", "Otro" }));
        cmbPatientCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPatientBirthdayLayout = new javax.swing.GroupLayout(jPanelPatientBirthday);
        jPanelPatientBirthday.setLayout(jPanelPatientBirthdayLayout);
        jPanelPatientBirthdayLayout.setHorizontalGroup(
            jPanelPatientBirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPatientBirthdayLayout.setVerticalGroup(
            jPanelPatientBirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtPatientLastName)
                            .addComponent(jPanelPatientBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPatientCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientCity, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPatientBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPatientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbPatientCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 332, -1));

        jPanel3.setBackground(new java.awt.Color(61, 25, 119));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tel. 1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tel. 2");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Datos de contacto");

        txtPatientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientPhoneActionPerformed(evt);
            }
        });

        txtPatientPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientPhone2ActionPerformed(evt);
            }
        });

        txtPatientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientEmailActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Redes");

        txtPatientSocials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientSocialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(24, 24, 24)
                                .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientSocials, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPatientPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtPatientSocials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 720, 180));

        jPanel4.setBackground(new java.awt.Color(61, 25, 119));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tarifa dif.");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Día");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Horario");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Datos de sesión");

        cmbPatientSessionDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        cmbPatientSessionDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientSessionDay1ActionPerformed(evt);
            }
        });

        cmbPatientSessionDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        cmbPatientSessionDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientSessionDay2ActionPerformed(evt);
            }
        });

        cmbPatientSessionHour1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));
        cmbPatientSessionHour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientSessionHour1ActionPerformed(evt);
            }
        });

        cmbPatientSessionHour2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));
        cmbPatientSessionHour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientSessionHour2ActionPerformed(evt);
            }
        });

        cmbPatientSessionDay3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        cmbPatientSessionDay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientSessionDay3ActionPerformed(evt);
            }
        });

        cmbPatientSessionHour3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Modalidad");

        cmbPatientSessionMode1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        cmbPatientSessionMode2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        cmbPatientSessionMode3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        cmbPatientCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos", "Dolares", "Euros" }));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Derivado por");

        txtPatientDerivedFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientDerivedFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPatientSessionDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPatientSessionHour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(cmbPatientSessionMode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientDerivedFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbPatientSessionDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatientSessionHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatientSessionMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbPatientSessionDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatientSessionHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatientSessionMode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientDifBillingRate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPatientCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPatientSessionDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionHour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionMode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPatientSessionDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPatientSessionDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientSessionMode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPatientDifBillingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtPatientDerivedFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 320, 390));

        jPanel6.setBackground(new java.awt.Color(61, 25, 119));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setBackground(new java.awt.Color(61, 25, 119));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Obs. Iniciales");

        txtPatientInitialObservations.setColumns(20);
        txtPatientInitialObservations.setRows(5);
        jScrollPane1.setViewportView(txtPatientInitialObservations);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 340, 390));

        btnSaveNewPatientForm.setBackground(new java.awt.Color(61, 25, 119));
        btnSaveNewPatientForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaveNewPatientForm.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveNewPatientForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\diskette.png")); // NOI18N
        btnSaveNewPatientForm.setText(" Guardar");
        btnSaveNewPatientForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewPatientFormActionPerformed(evt);
            }
        });
        bg.add(btnSaveNewPatientForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 580, 140, 56));

        btnClearPatientForm.setBackground(new java.awt.Color(61, 25, 119));
        btnClearPatientForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClearPatientForm.setForeground(new java.awt.Color(255, 255, 255));
        btnClearPatientForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\clean.png")); // NOI18N
        btnClearPatientForm.setText(" Limpiar");
        btnClearPatientForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPatientFormActionPerformed(evt);
            }
        });
        bg.add(btnClearPatientForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 140, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtPatientLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientLastNameActionPerformed

    private void txtPatientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientAddressActionPerformed

    private void txtPatientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientCityActionPerformed

    private void cmbPatientGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientGenderActionPerformed

    private void cmbPatientCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientCountryActionPerformed

    private void txtPatientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientPhoneActionPerformed

    private void txtPatientPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientPhone2ActionPerformed

    private void txtPatientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientEmailActionPerformed

    private void txtPatientSocialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientSocialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientSocialsActionPerformed

    private void cmbPatientSessionDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientSessionDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientSessionDay1ActionPerformed

    private void cmbPatientSessionDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientSessionDay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientSessionDay2ActionPerformed

    private void cmbPatientSessionHour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientSessionHour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientSessionHour1ActionPerformed

    private void cmbPatientSessionDay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientSessionDay3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientSessionDay3ActionPerformed

    private void txtPatientDerivedFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientDerivedFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientDerivedFromActionPerformed

    private void btnSaveNewPatientFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewPatientFormActionPerformed
        String name = txtPatientName.getText();
        String lastName = txtPatientLastName.getText();
        String address = txtPatientAddress.getText();
        String city = txtPatientCity.getText();
        String phone = txtPatientPhone.getText();
        String phone2 = txtPatientPhone2.getText();
        String email = txtPatientEmail.getText();
        String socials = txtPatientSocials.getText();
        String derivedFrom = txtPatientDerivedFrom.getText();
        String initialObservations = txtPatientInitialObservations.getText();
        Date birthday = dtPatientBirthday.getDate();
        String gender = (String) cmbPatientGender.getSelectedItem();
        String avatar = "/resources/public/profile/defaultAvatar.jpg";
        String country = (String) cmbPatientCountry.getSelectedItem();
        
        Patient newPatient = new Patient(name,
            lastName,
            birthday,
            gender,
            avatar,
            address,
            city,
            country,
            phone,
            phone2,
            email,
            socials,
            derivedFrom,
            initialObservations);
        
        try{
            patientService.create(newPatient);
        
            String difBillingRate = txtPatientDifBillingRate.getText();
            String currency = (String) cmbPatientCurrency.getSelectedItem();

            if(cmbPatientSessionDay1.getSelectedIndex() != 0 && cmbPatientSessionHour1.getSelectedIndex() != 0){

                String sessionDay1 = (String) cmbPatientSessionDay1.getSelectedItem();
                DayOfWeek castedSessionDay1 = DateMapper.mapDay(sessionDay1);

                String sessionHour1 = (String) cmbPatientSessionHour1.getSelectedItem();
                LocalTime castedSessionHour1 = DateMapper.mapHour(sessionHour1);

                String sessionMode1 = (String) cmbPatientSessionMode1.getSelectedItem();


                Session newSession1 = new Session(newPatient,
            castedSessionDay1,
                castedSessionHour1,
                 castedSessionHour1.plusHours(1),
                sessionMode1,
                    difBillingRate,
                    currency    
                );

                sessionService.create(newSession1);
            }

            if(cmbPatientSessionDay2.getSelectedIndex() != 0 && cmbPatientSessionHour2.getSelectedIndex() != 0){
                String sessionDay2 = (String) cmbPatientSessionDay2.getSelectedItem();
                DayOfWeek castedSessionDay2 = DateMapper.mapDay(sessionDay2);

                String sessionHour2 = (String) cmbPatientSessionHour2.getSelectedItem();
                LocalTime castedSessionHour2 = DateMapper.mapHour(sessionHour2);

                String sessionMode2 = (String) cmbPatientSessionMode2.getSelectedItem();

                Session newSession2 = new Session(newPatient,
            castedSessionDay2,
                castedSessionHour2,
                 castedSessionHour2.plusHours(1),
                sessionMode2,
                    difBillingRate,
                    currency    
                );

                sessionService.create(newSession2);
            }

            if(cmbPatientSessionDay3.getSelectedIndex() != 0 && cmbPatientSessionHour3.getSelectedIndex() != 0){
                String sessionDay3 = (String) cmbPatientSessionDay3.getSelectedItem();
                DayOfWeek castedSessionDay3 = DateMapper.mapDay(sessionDay3);

                String sessionHour3 = (String) cmbPatientSessionHour3.getSelectedItem();
                LocalTime castedSessionHour3 = DateMapper.mapHour(sessionHour3);

                String sessionMode3 = (String) cmbPatientSessionMode3.getSelectedItem();

                Session newSession3 = new Session(newPatient,
            castedSessionDay3,
                castedSessionHour3,
                 castedSessionHour3.plusHours(1),
                sessionMode3,
                    difBillingRate,
                    currency    
                );

                sessionService.create(newSession3);
            }

            CustomMessageDialog.show(
                this,
                "Paciente guardado correctamente",
                UIManager.getIcon("OptionPane.informationIcon"),
                new Color(46, 204, 113),
                Color.WHITE,
                true,
                2000,
                CustomMessageDialog.Position.DOWN_RIGHT
            );
        }
        catch(Exception err){
            System.out.println("Paciente no guardado");
        }

    }//GEN-LAST:event_btnSaveNewPatientFormActionPerformed

    private void btnClearPatientFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPatientFormActionPerformed
        txtPatientName.setText("");
        txtPatientLastName.setText("");
        txtPatientAddress.setText("");
        txtPatientCity.setText("");
        txtPatientPhone.setText("");
        txtPatientPhone2.setText("");
        txtPatientEmail.setText("");
        txtPatientSocials.setText("");
        txtPatientDifBillingRate.setText("");
        txtPatientDerivedFrom.setText("");
        txtPatientInitialObservations.setText("");
        dtPatientBirthday.setDate(null);
        cmbPatientGender.setSelectedIndex(0);
        cmbPatientCountry.setSelectedIndex(0);
        cmbPatientCurrency.setSelectedIndex(0);
        cmbPatientSessionDay1.setSelectedIndex(0);
        cmbPatientSessionDay2.setSelectedIndex(0);
        cmbPatientSessionDay3.setSelectedIndex(0);
        cmbPatientSessionHour1.setSelectedIndex(0);
        cmbPatientSessionHour2.setSelectedIndex(0);
        cmbPatientSessionHour3.setSelectedIndex(0);
        cmbPatientSessionMode1.setSelectedIndex(0);
        cmbPatientSessionMode2.setSelectedIndex(0);
        cmbPatientSessionMode3.setSelectedIndex(0);

    }//GEN-LAST:event_btnClearPatientFormActionPerformed

    private void cmbPatientSessionHour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientSessionHour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientSessionHour2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnClearPatientForm;
    private javax.swing.JButton btnSaveNewPatientForm;
    private javax.swing.JComboBox<String> cmbPatientCountry;
    private javax.swing.JComboBox<String> cmbPatientCurrency;
    private javax.swing.JComboBox<String> cmbPatientGender;
    private javax.swing.JComboBox<String> cmbPatientSessionDay1;
    private javax.swing.JComboBox<String> cmbPatientSessionDay2;
    private javax.swing.JComboBox<String> cmbPatientSessionDay3;
    private javax.swing.JComboBox<String> cmbPatientSessionHour1;
    private javax.swing.JComboBox<String> cmbPatientSessionHour2;
    private javax.swing.JComboBox<String> cmbPatientSessionHour3;
    private javax.swing.JComboBox<String> cmbPatientSessionMode1;
    private javax.swing.JComboBox<String> cmbPatientSessionMode2;
    private javax.swing.JComboBox<String> cmbPatientSessionMode3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelPatientBirthday;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientCity;
    private javax.swing.JTextField txtPatientDerivedFrom;
    private javax.swing.JTextField txtPatientDifBillingRate;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextArea txtPatientInitialObservations;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientPhone2;
    private javax.swing.JTextField txtPatientSocials;
    // End of variables declaration//GEN-END:variables
}
