/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bo.patientmanager.gui;

import com.bo.patientmanager.gui.allPatientsViews.SeeAllPatientsPane;
import com.bo.patientmanager.gui.component.BackgroundPanel;
import com.bo.patientmanager.service.ServiceManager;
import jakarta.persistence.EntityManagerFactory;
import java.awt.BorderLayout;
import persistence.JPAUtil;


/**
 *
 * @author Documentos
 */
public class MainWindow extends javax.swing.JFrame {
    
    private BackgroundPanel bgContent;
    
    EntityManagerFactory em = JPAUtil.getEntityManagerFactory();
    
    ServiceManager serviceManager = new ServiceManager(em);

    /**
     * Creates new form Main
     */
    public MainWindow() {
        
        initComponents();

        content.removeAll();
        content.setLayout(new BorderLayout());

        bgContent = new BackgroundPanel("/public/bg/bg_nodes.jpg");
        bgContent.setLayout(new BorderLayout());

        content.add(bgContent, BorderLayout.CENTER);
        
        bgContent.setView(new HomePane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBg = new javax.swing.JPanel();
        menuBg = new javax.swing.JPanel();
        btnSearchClinicHistory = new javax.swing.JButton();
        btnGetAllPatients = new javax.swing.JButton();
        btnSearchPatient = new javax.swing.JButton();
        btnLoadNewPatient = new javax.swing.JButton();
        btnLoadNewClinicHistory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainBg.setBackground(new java.awt.Color(232, 216, 255));
        mainBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBg.setBackground(new java.awt.Color(0, 0, 102));
        menuBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchClinicHistory.setBackground(new java.awt.Color(61, 25, 119));
        btnSearchClinicHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchClinicHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchClinicHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\search (1).png")); // NOI18N
        btnSearchClinicHistory.setText("Buscar Historia Clinica");
        btnSearchClinicHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClinicHistoryActionPerformed(evt);
            }
        });
        menuBg.add(btnSearchClinicHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 250, 56));

        btnGetAllPatients.setBackground(new java.awt.Color(61, 25, 119));
        btnGetAllPatients.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGetAllPatients.setForeground(new java.awt.Color(255, 255, 255));
        btnGetAllPatients.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\user.png")); // NOI18N
        btnGetAllPatients.setText("Ver Pacientes");
        btnGetAllPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllPatientsActionPerformed(evt);
            }
        });
        menuBg.add(btnGetAllPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 56));

        btnSearchPatient.setBackground(new java.awt.Color(61, 25, 119));
        btnSearchPatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchPatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\search.png")); // NOI18N
        btnSearchPatient.setText("Buscar Paciente");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });
        menuBg.add(btnSearchPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, 56));

        btnLoadNewPatient.setBackground(new java.awt.Color(61, 25, 119));
        btnLoadNewPatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoadNewPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadNewPatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\add.png")); // NOI18N
        btnLoadNewPatient.setText("Cargar Paciente");
        btnLoadNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNewPatientActionPerformed(evt);
            }
        });
        menuBg.add(btnLoadNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 56));

        btnLoadNewClinicHistory.setBackground(new java.awt.Color(61, 25, 119));
        btnLoadNewClinicHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoadNewClinicHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadNewClinicHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\contract.png")); // NOI18N
        btnLoadNewClinicHistory.setText("Cargar Sesión");
        btnLoadNewClinicHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNewClinicHistoryActionPerformed(evt);
            }
        });
        menuBg.add(btnLoadNewClinicHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 210, 56));

        btnExit.setBackground(new java.awt.Color(61, 25, 119));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\log-out.png")); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        menuBg.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 140, 56));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/bg/bg_nodes_menu.jpg"))); // NOI18N
        menuBg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        mainBg.add(menuBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Downloads\\33114809_rm251-mind-15-e3.jpg")); // NOI18N
        mainBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 100));

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(61, 25, 119));
        title.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Historias Clinicas");
        content.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        mainBg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoadNewClinicHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNewClinicHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadNewClinicHistoryActionPerformed

    private void btnLoadNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNewPatientActionPerformed

        //creates and opens the loading window for a new Patient
        LoadPatientForm loadPatientFormPane = new LoadPatientForm(serviceManager);

        bgContent.setView(loadPatientFormPane);

    }//GEN-LAST:event_btnLoadNewPatientActionPerformed

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnGetAllPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllPatientsActionPerformed
        // TODO add your handling code here:
        bgContent.setView(new SeeAllPatientsPane(serviceManager, bgContent));
    }//GEN-LAST:event_btnGetAllPatientsActionPerformed

    private void btnSearchClinicHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClinicHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClinicHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetAllPatients;
    private javax.swing.JButton btnLoadNewClinicHistory;
    private javax.swing.JButton btnLoadNewPatient;
    private javax.swing.JButton btnSearchClinicHistory;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainBg;
    private javax.swing.JPanel menuBg;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
