/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bo.patientmanager.gui;

/**
 *
 * @author Documentos
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSearchClinicHistory = new javax.swing.JButton();
        btnGetAllPatients = new javax.swing.JButton();
        btnSearchPatient = new javax.swing.JButton();
        btnLoadNewPatient = new javax.swing.JButton();
        btnLoadNewClinicHistory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 198, 213));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Historias Clinicas");

        jPanel2.setBackground(new java.awt.Color(206, 198, 213));

        btnSearchClinicHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchClinicHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\search (1).png")); // NOI18N
        btnSearchClinicHistory.setText("Buscar Historia Clinica");
        btnSearchClinicHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClinicHistoryActionPerformed(evt);
            }
        });

        btnGetAllPatients.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGetAllPatients.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\user.png")); // NOI18N
        btnGetAllPatients.setText("Ver Pacientes");
        btnGetAllPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllPatientsActionPerformed(evt);
            }
        });

        btnSearchPatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchPatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\search.png")); // NOI18N
        btnSearchPatient.setText("Buscar Paciente");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        btnLoadNewPatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoadNewPatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\add.png")); // NOI18N
        btnLoadNewPatient.setText("Cargar Paciente");
        btnLoadNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNewPatientActionPerformed(evt);
            }
        });

        btnLoadNewClinicHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoadNewClinicHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\contract.png")); // NOI18N
        btnLoadNewClinicHistory.setText("Cargar Historia Clinica");
        btnLoadNewClinicHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNewClinicHistoryActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\log-out.png")); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Documentos\\Desktop\\Projects\\BringOnline\\Ro\\patientManager\\src\\main\\resources\\public\\icons\\logo (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadNewClinicHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClinicHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetAllPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnGetAllPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchClinicHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadNewClinicHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoadNewClinicHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNewClinicHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadNewClinicHistoryActionPerformed

    private void btnLoadNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNewPatientActionPerformed

        //creates and opens the loading window for a new Patient
        LoadPatient windowLoadPatient = new LoadPatient();
        windowLoadPatient.setVisible(true);
        windowLoadPatient.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLoadNewPatientActionPerformed

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnGetAllPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllPatientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetAllPatientsActionPerformed

    private void btnSearchClinicHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClinicHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClinicHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetAllPatients;
    private javax.swing.JButton btnLoadNewClinicHistory;
    private javax.swing.JButton btnLoadNewPatient;
    private javax.swing.JButton btnSearchClinicHistory;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
