/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bo.patientmanager.gui.allPatientsViews;

import com.bo.patientmanager.model.PatientRelativeRelation;
import com.bo.patientmanager.model.RelativeObservation;
import com.bo.patientmanager.service.PatientRelativeRelationService;
import com.bo.patientmanager.service.RelativeObservationService;
import com.bo.patientmanager.service.ServiceManager;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bring Online
 */
public class RelativeFrame extends javax.swing.JFrame {
    
    private Long relationId = null;
    PatientRelativeRelationService patientRelativeRelationService = null;
    RelativeObservationService relativeObservationService = null;

    /**
     * Creates new form FamiliarFrame
     */
    public RelativeFrame(ServiceManager serviceManager, Long relationId) {
        initComponents();
        
        this.relationId = relationId;
        patientRelativeRelationService = serviceManager.getPatientRelativeRelationService();
        relativeObservationService = serviceManager.getRelativeObservationService();

        initComponents();
        loadData();
    }
    
    private void loadData(){

        PatientRelativeRelation rel = patientRelativeRelationService.findById(relationId);

        name.setText(rel.getRelative().getName());
        lastName.setText(rel.getRelative().getLastName());
        phone1.setText(rel.getRelative().getPhone1());
        phone2.setText(rel.getRelative().getPhone2());
        gender.setText(rel.getRelative().getGender());
        address.setText(rel.getRelative().getAddress());
        city.setText(rel.getRelative().getCity());
        country.setText(rel.getRelative().getCountry());
        
        loadObservations();
    }

    private void loadObservations(){
        
        DefaultListModel<RelativeObservation> obsModel = new DefaultListModel<>();
        lstObservations.setModel(obsModel);

        obsModel.clear();

        List<RelativeObservation> list = relativeObservationService.findByRelation(relationId);

        for(RelativeObservation o : list){
            obsModel.addElement(o);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lastName = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        derivedFrom = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        derivedTo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        socials = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        phone2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstObservations = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(61, 25, 119));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastName.setBackground(new java.awt.Color(61, 25, 119));
        lastName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("paciente ");
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 50));

        birthday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthday.setForeground(new java.awt.Color(255, 255, 255));
        birthday.setText("Fecha");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("(Edad)");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Dirección");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        city.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setText("Ciudad");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Genero");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        country.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("País");
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        derivedFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        derivedFrom.setForeground(new java.awt.Color(255, 255, 255));
        derivedFrom.setText("Derivado por:");
        jPanel1.add(derivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        state.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        state.setForeground(new java.awt.Color(255, 255, 255));
        state.setText("Estado");
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        name.setBackground(new java.awt.Color(61, 25, 119));
        name.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nombre ");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 60));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Derivado a:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Derivado por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha de nacimiento");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(Edad)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Genero");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Dirección");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ciudad");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("País");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        derivedTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        derivedTo.setForeground(new java.awt.Color(255, 255, 255));
        derivedTo.setText("Derivado a:");

        jPanel2.setBackground(new java.awt.Color(61, 25, 119));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        socials.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        socials.setForeground(new java.awt.Color(255, 255, 255));
        socials.setText("Redes:");
        jPanel2.add(socials, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email:");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        phone1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 255, 255));
        phone1.setText("Telefono 1:");
        jPanel2.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        phone2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone2.setForeground(new java.awt.Color(255, 255, 255));
        phone2.setText("Telefono 2:");
        jPanel2.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Telefono 1:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Telefono 2:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Email:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Redes:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel4.setBackground(new java.awt.Color(61, 25, 119));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Observaciones:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jScrollPane1.setViewportView(lstObservations);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(derivedTo)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addComponent(derivedTo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel city;
    private javax.swing.JLabel country;
    private javax.swing.JLabel derivedFrom;
    private javax.swing.JLabel derivedTo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JList<com.bo.patientmanager.model.RelativeObservation> lstObservations;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone2;
    private javax.swing.JLabel socials;
    private javax.swing.JLabel state;
    // End of variables declaration//GEN-END:variables
}
