/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bo.patientmanager.gui.allPatientsViews;

import com.bo.patientmanager.gui.HomePane;
import com.bo.patientmanager.gui.component.BackgroundPanel;
import com.bo.patientmanager.model.PatientRelativeRelation;
import com.bo.patientmanager.model.RelativeObservation;
import com.bo.patientmanager.service.PatientRelativeRelationService;
import com.bo.patientmanager.service.RelativeObservationService;
import com.bo.patientmanager.service.ServiceManager;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bring Online
 */
public class RelativeDataFrame extends javax.swing.JFrame {
    
    private Long relationId = null;
    PatientRelativeRelationService patientRelativeRelationService = null;
    RelativeObservationService relativeObservationService = null;

    /**
     * Creates new form FamiliarFrame
     */
    public RelativeDataFrame(ServiceManager serviceManager, Long relationId) {
        initComponents();
        
        BackgroundPanel.setDefaultView(content, view);
        
        this.relationId = relationId;
        patientRelativeRelationService = serviceManager.getPatientRelativeRelationService();
        relativeObservationService = serviceManager.getRelativeObservationService();

        loadData();
    }
    
    private void loadData(){

        PatientRelativeRelation rel = patientRelativeRelationService.findById(relationId);

        name.setText(rel.getRelative().getName());
        lastName.setText(rel.getRelative().getLastName());
        phone1.setText(rel.getRelative().getPhone1());
        phone2.setText(rel.getRelative().getPhone2());
        gender.setText(rel.getRelative().getGender());
        address.setText(rel.getRelative().getAddress());
        city.setText(rel.getRelative().getCity());
        country.setText(rel.getRelative().getCountry());
        
        loadObservations();
    }

    private void loadObservations(){
        
        DefaultListModel<RelativeObservation> obsModel = new DefaultListModel<>();
        lstObservations.setModel(obsModel);

        obsModel.clear();

        List<RelativeObservation> list = relativeObservationService.findByRelation(relationId);

        for(RelativeObservation o : list){
            obsModel.addElement(o);
        }
    }
    /**
        private void loadObservations(Patient patient){

        observationsModel.clear();        
        // --- Observaciones
        List<RelativeObservation> allObservationsData = serviceManager.getRelativeObservationService().findByPatientRelativeRelation(patient.getPatientId());

        for(RelativeObservation observation : allObservationsData){
            observationsModel.addElement(observation);
        }
    };
    * **/
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        view = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lastName = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        derivedFrom = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        socials = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        phone2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstObservations = new javax.swing.JList<>();
        btnAddObservation = new javax.swing.JButton();
        btnEditObservation = new javax.swing.JButton();
        btnDltObservation = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 25, 119));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastName.setBackground(new java.awt.Color(61, 25, 119));
        lastName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("paciente ");
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 50));

        birthday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthday.setForeground(new java.awt.Color(255, 255, 255));
        birthday.setText("Fecha");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("(Edad)");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Dirección");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        city.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setText("Ciudad");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Genero");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        country.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("País");
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        derivedFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        derivedFrom.setForeground(new java.awt.Color(255, 255, 255));
        derivedFrom.setText("Derivado por:");
        jPanel1.add(derivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        state.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        state.setForeground(new java.awt.Color(255, 255, 255));
        state.setText("Estado");
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        name.setBackground(new java.awt.Color(61, 25, 119));
        name.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nombre ");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 60));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Derivado a:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Derivado por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha de nacimiento");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(Edad)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Genero");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Dirección");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ciudad");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("País");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jPanel2.setBackground(new java.awt.Color(61, 25, 119));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        socials.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        socials.setForeground(new java.awt.Color(255, 255, 255));
        socials.setText("Redes:");
        jPanel2.add(socials, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email:");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        phone1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 255, 255));
        phone1.setText("Telefono 1:");
        jPanel2.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        phone2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone2.setForeground(new java.awt.Color(255, 255, 255));
        phone2.setText("Telefono 2:");
        jPanel2.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Telefono 1:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Telefono 2:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Email:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Redes:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel4.setBackground(new java.awt.Color(61, 25, 119));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Observaciones:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jScrollPane1.setViewportView(lstObservations);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 380, 260));

        btnAddObservation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAddObservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/icons/add (1).png"))); // NOI18N
        btnAddObservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObservationActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        btnEditObservation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEditObservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/icons/edit.png"))); // NOI18N
        btnEditObservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditObservationActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        btnDltObservation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDltObservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/icons/remove.png"))); // NOI18N
        btnDltObservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDltObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltObservationActionPerformed(evt);
            }
        });
        jPanel4.add(btnDltObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(viewLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1140, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnAddObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObservationActionPerformed
        // TODO add your handling code here:
        PatientRelativeRelation rel = patientRelativeRelationService.findById(relationId);

        ObservationAddForm observationAddFormWindow = new ObservationAddForm(relativeObservationService, rel, this::loadObservations);
        observationAddFormWindow.setVisible(true);
        observationAddFormWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddObservationActionPerformed

    private void btnEditObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditObservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditObservationActionPerformed

    private void btnDltObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltObservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDltObservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton btnAddObservation;
    private javax.swing.JButton btnDltObservation;
    private javax.swing.JButton btnEditObservation;
    private javax.swing.JLabel city;
    private javax.swing.JPanel content;
    private javax.swing.JLabel country;
    private javax.swing.JLabel derivedFrom;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JList<com.bo.patientmanager.model.RelativeObservation> lstObservations;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone2;
    private javax.swing.JLabel socials;
    private javax.swing.JLabel state;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
