/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bo.patientmanager.gui.theme;

/**
 *
 * @author Bring Online
 */
public class ThemePickerPane extends javax.swing.JPanel {

    /**
     * Creates new form ThemePickerPane
     */
    public ThemePickerPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new javax.swing.JPanel();
        btnNodeTheme = new javax.swing.JButton();
        btnStarsTheme = new javax.swing.JButton();

        btnNodeTheme.setText("Nodos");
        btnNodeTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodeThemeActionPerformed(evt);
            }
        });

        btnStarsTheme.setText("Estrellas");
        btnStarsTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStarsThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStarsTheme)
                    .addComponent(btnNodeTheme))
                .addContainerGap(677, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnNodeTheme)
                .addGap(18, 18, 18)
                .addComponent(btnStarsTheme)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNodeThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodeThemeActionPerformed
        // TODO add your handling code here:
        ThemeManager.setTheme(AppTheme.NODES);
    }//GEN-LAST:event_btnNodeThemeActionPerformed

    private void btnStarsThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStarsThemeActionPerformed
        // TODO add your handling code here:
        ThemeManager.setTheme(AppTheme.STARS);
    }//GEN-LAST:event_btnStarsThemeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNodeTheme;
    private javax.swing.JButton btnStarsTheme;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
